name: Merge master into develop
on:
  push:
    branches:
      - master
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git checkout master
      - run: git fetch
      - run: git pull
      - run: git checkout qa
      - run: git merge master
