name: Merge master into develop
on:
  push:
    branches:
      - master
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: get checkout master
      - run: git fetch
      - run: git pull
      - run: git checkout develop
      - run: git merge master
